### ISSUE TITLE
Hooking to add categories

### ISSUE THREAD

**Issue by bhackel** [PoomSmart/YouGroupSettings#2]
Hello, I am having trouble adding new settings categories. This is my current implementation:

https://github.com/bhackel/YTLitePlus/blob/dae93861bb9fe531e1b5785dd5ab001f4bbc968a/Source/Settings.xm#L41-L58

```obj-c
// Add both YTLite and YTLitePlus to YouGroupSettings
static const NSInteger YTLitePlusSection = 788;
static const NSInteger YTLiteSection = 789;
%hook YTSettingsGroupData
+ (NSMutableArray <NSNumber *> *)tweaks {
    NSLog(@"bhackel: called hooked 'tweaks' method.");
    NSMutableArray <NSNumber *> *originalTweaks = %orig;

    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [originalTweaks addObject:@(YTLitePlusSection)];
        [originalTweaks addObject:@(YTLiteSection)];
    });

    // Return the modified array.
    return originalTweaks;
}
%end
```

When checking the output of this method in FLEX, I can see that the array has not been modified from the original seven (404, 517, 1080, 200, 2168, 1222, 500). I can also see that there is no log caused by the NSLog command.

My current ideas are that either my implementation is wrong, or that new'd methods cannot be hooked.
Thanks for your assistance.

**Comment by PoomSmart** [comment]
Did you `dlopen` this tweak?

**Comment by bhackel** [comment]
I am not sure since I haven’t written much of the other code. I will try to figure it out now.

**Comment by bhackel** [comment]
Okay it worked, I added
```obj-c
dlopen([[NSString stringWithFormat:@"%@/Frameworks/YouGroupSettings.dylib", [[NSBundle mainBundle] bundlePath]] UTF8String], RTLD_LAZY);
```
to my %ctor and now the method is able to be hooked. Thank you
