### ISSUE TITLE
YouGroupSettings operates unstably

### ISSUE THREAD

**Issue by thaibm92** [PoomSmart/YouGroupSettings#4]
Hello PoomSmart, thank you for developing such great applications.
However, this YouGroupSettings application seems to operate unstably. I tried injecting it into YouTube IPA v19.47.7 along with YouTube X, and the results were:

On the first launch of the application, YouGroup did not work (when the login icon was still in the top-right corner of the screen).
On the second launch of the YouTube application, it worked (the Google login logo appeared in the bottom-right corner of the MENU screen).

However, after closing the application and reopening it 15–30 minutes later, YouGroupSettings completely stops working. I hope you can identify the cause and fix it. Thank you very much!

**Comment by PoomSmart** [comment]
If I understood correctly, you need to ensure `YTColdConfig.mainAppCoreClientEnableCairoSettings` is enabled via YTABConfig tweak.

**Comment by thaibm92** [comment]
> If I understood correctly, you need to ensure `YTColdConfig.mainAppCoreClientEnableCairoSettings` is enabled via YTABConfig tweak.

You were right, I turned it on, and it worked again. However, the icons for other titles disappeared, making it look unattractive. Before enabling `YTColdConfig.mainAppCoreClientEnableCairoSettings`, YouGroupSettings worked perfectly for the first time. Do you know the reason why?
![image](https://github.com/user-attachments/assets/31dbe706-3872-4a81-96b0-5279c8dcddd2)
![image](https://github.com/user-attachments/assets/1126e88b-f969-49a6-9792-6cf2385d79e1)

**Comment by PoomSmart** [comment]
The reason for missing icons is largely due to YouTube itself. The settings you see are controlled server-side, meaning YouTube may not provide all the icons for all the settings. Forcing that A/B flag alone isn't enough. Your best bet is to ensure that the flag is set to false.

**Comment by thaibm92** [comment]
I tried checking a case where I didn't log in to a Google account on YouTube and removed the code below, and it worked fine. Do you know if there's any issue with this code? If this code isn't used, the Gmail account can't be remembered when exiting the application.

// Keychain patching
static NSString *accessGroupID() {
    NSDictionary *query = [NSDictionary dictionaryWithObjectsAndKeys:
                           (__bridge NSString *)kSecClassGenericPassword, (__bridge NSString *)kSecClass,
                           @"bundleSeedID", kSecAttrAccount,
                           @"", kSecAttrService,
                           (id)kCFBooleanTrue, kSecReturnAttributes,
                           nil];
    CFDictionaryRef result = nil;
    OSStatus status = SecItemCopyMatching((__bridge CFDictionaryRef)query, (CFTypeRef *)&result);
    if (status == errSecItemNotFound)
        status = SecItemAdd((__bridge CFDictionaryRef)query, (CFTypeRef *)&result);
        if (status != errSecSuccess)
            return nil;
    NSString *accessGroup = [(__bridge NSDictionary *)result objectForKey:(__bridge NSString *)kSecAttrAccessGroup];

    return accessGroup;
}

// Fix login for YouTube 18.13.2 and higher
%hook SSOKeychainHelper
+ (NSString *)accessGroup {
    return accessGroupID();
}
+ (NSString *)sharedAccessGroup {
    return accessGroupID();
}
%end

// Fix login for YouTube 17.33.2 and higher
%hook SSOKeychainCore
+ (NSString *)accessGroup {
    return accessGroupID();
}

+ (NSString *)sharedAccessGroup {
    return accessGroupID();
}
%end

**Comment by PoomSmart** [comment]
Then this all is about sideloading YT correctly and not about YouGroupSettings itself.

I haven't come up with a solution around sideloading correctly yet. Your code looks correct but I don't have any more suggestions for now.
